import {
    CREATE_USER,
    UPDATE_USER,
    SHOW_USER,
    DELETE_USER,
    SUPER_USER
} from './userPermissions'

import {
    CREATE_TICKET,
    UPDATE_TICKET,
    SHOW_TICKET,
    DELETE_TICKET,
    SUPER_TICKET
} from './ticketPermissions'

export {
    //USER PERMISSIONS
    CREATE_USER,
    UPDATE_USER,
    SHOW_USER,
    DELETE_USER,
    SUPER_USER,

    //TICKET PERMISSIONS
    CREATE_TICKET,
    UPDATE_TICKET,
    SHOW_TICKET,
    DELETE_TICKET,
    SUPER_TICKET
}